"""
Tests for the cleanup of videos/ when the server starts.

Regression: startup deleted every .mp4 in videos/, while main.py told users
to put their background clip (minecraft1.mp4) there. Only videos the app
generated, which main.generate() names <uuid4>.mp4, may be removed.
"""

from uuid import uuid4

from fastapi.testclient import TestClient

import server


def run_startup():
    with TestClient(server.app):  # entering the client runs the startup hook
        pass


class TestStartupCleanup:
    def test_removes_leftover_generated_videos(self, tmp_path, monkeypatch):
        videos = tmp_path / "videos"
        videos.mkdir()
        leftover = videos / f"{uuid4()}.mp4"
        leftover.write_bytes(b"generated by a previous run")
        monkeypatch.setattr(server, "VIDEOS_DIR", str(videos))

        run_startup()

        assert not leftover.exists()

    def test_keeps_user_supplied_media(self, tmp_path, monkeypatch):
        videos = tmp_path / "videos"
        videos.mkdir()
        background = videos / "minecraft1.mp4"
        background.write_bytes(b"background clip")
        other = videos / "intro.mp4"
        other.write_bytes(b"some other clip")
        monkeypatch.setattr(server, "VIDEOS_DIR", str(videos))

        run_startup()

        assert background.read_bytes() == b"background clip"
        assert other.exists()
